name: Take screnshotsction

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '15 6 * * MON'

jobs:
  scheduled:
    runs-on: ubuntu-24.04
    timeout-minutes: 100

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - name: Take shots
      run: |
        shot-scraper pdf --timeout 10000 --fail --format A4 -o "shots/$(date +%F)-imprint.pdf" "https://www.komoot.com/de-de/imprint"
        shot-scraper pdf --timeout 10000 --fail --format A4 -o "shots/$(date +%F)-terms-of-service.pdf" "https://www.komoot.com/de-de/terms-of-service"
        shot-scraper pdf --timeout 10000 --fail --format A4 -o "shots/$(date +%F)-privacy.pdf" "https://www.komoot.com/de-de/privacy"
        shot-scraper pdf --timeout 10000 --fail --format A4 -o "shots/$(date +%F)-shop.pdf" "https://www.komoot.com/de-de/shop"
        shot-scraper pdf --timeout 10000 --fail --format A4 -o "shots/$(date +%F)-home.pdf" "https://www.komoot.com/de-de"
    - name: Commit and push if anything changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest: ${timestamp}" || exit 0
        git pull --rebase
        git push
